"""Add social login fields to User model

Revision ID: 66380f3f209b
Revises: fc7120e343a0
Create Date: 2026-02-03 16:30:01.660402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '66380f3f209b'
down_revision: Union[str, Sequence[str], None] = 'fc7120e343a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provider', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('social_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'social_id')
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###
